# Generated by Django 3.1.7 on 2021-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('price', models.CharField(max_length=50)),
                ('Resolution', models.IntegerField()),
                ('no_of_Active_Screens', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('show_type', models.CharField(max_length=50)),
                ('story', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('production_Date', models.DateField()),
                ('rating', models.FloatField()),
                ('classification', models.CharField(max_length=50)),
                ('publish_Date', models.DateField()),
                ('video_Source', models.URLField()),
                ('poster', models.URLField()),
                ('language', models.CharField(max_length=50)),
                ('actors', models.ManyToManyField(to='Netflix.Actor')),
                ('authors', models.ManyToManyField(to='Netflix.Author')),
                ('directors', models.ManyToManyField(to='Netflix.Director')),
                ('genres', models.ManyToManyField(to='Netflix.Genre')),
                ('prizes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Netflix.prize')),
                ('producers', models.ManyToManyField(to='Netflix.Producer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Rating', models.IntegerField()),
                ('Show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.show')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.user')),
            ],
        ),
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.show')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.user')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Current_Duration', models.DurationField()),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.user')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.show')),
            ],
        ),
    ]
