# Generated by Django 3.1.7 on 2021-04-06 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('price', models.CharField(max_length=50)),
                ('Resolution', models.IntegerField()),
                ('no_of_Active_Screens', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('register_date', models.DateField()),
                ('avatar', models.TextField()),
                ('payment', models.DateField()),
                ('membership_Start_Date', models.DateField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('show_type', models.CharField(max_length=50)),
                ('story', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('production_Date', models.DateField()),
                ('rating', models.FloatField()),
                ('classification', models.CharField(max_length=50)),
                ('publish_Date', models.DateField()),
                ('video_Source', models.URLField()),
                ('poster', models.URLField()),
                ('language', models.CharField(max_length=50)),
                ('actors', models.ManyToManyField(to='Netflix.Actor')),
                ('authors', models.ManyToManyField(to='Netflix.Author')),
                ('directors', models.ManyToManyField(to='Netflix.Director')),
                ('genres', models.ManyToManyField(to='Netflix.Genre')),
                ('prizes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Netflix.prize')),
                ('producers', models.ManyToManyField(to='Netflix.Producer')),
            ],
        ),
        migrations.CreateModel(
            name='WatchLater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.show')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Rating', models.IntegerField()),
                ('Show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.show')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Current_Duration', models.DurationField()),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.profile')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.show')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.profile')),
            ],
        ),
    ]
