# Generated by Django 3.1.7 on 2021-04-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='Current_Duration',
            new_name='current_duration',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='User_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='watched',
            old_name='Show_id',
            new_name='show',
        ),
        migrations.RenameField(
            model_name='watched',
            old_name='User_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='watched',
            old_name='User_Rating',
            new_name='user_rating',
        ),
        migrations.RenameField(
            model_name='watchlater',
            old_name='Show_id',
            new_name='show',
        ),
        migrations.RenameField(
            model_name='watchlater',
            old_name='User_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='watchlater',
            unique_together={('show', 'user')},
        ),
    ]
