# Generated by Django 3.1.7 on 2021-04-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0002_auto_20210412_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='show_id',
            new_name='show',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='user_rating',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
