# Generated by Django 3.1.7 on 2021-04-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0003_auto_20210414_0110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watched',
            unique_together={('show', 'user')},
        ),
    ]
