# Generated by Django 3.1.7 on 2021-04-14 16:53

import Netflix.models.Show
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0004_auto_20210414_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='current_duration',
            new_name='Current_Duration',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='user',
            new_name='User_id',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='show',
            new_name='show_id',
        ),
        migrations.RenameField(
            model_name='watched',
            old_name='show',
            new_name='Show_id',
        ),
        migrations.RenameField(
            model_name='watched',
            old_name='user',
            new_name='User_id',
        ),
        migrations.RenameField(
            model_name='watchlater',
            old_name='show',
            new_name='Show_id',
        ),
        migrations.RenameField(
            model_name='watchlater',
            old_name='user',
            new_name='User_id',
        ),
        migrations.AddField(
            model_name='watched',
            name='User_Rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='show',
            name='rating',
            field=models.FloatField(validators=[Netflix.models.Show.validate_interval]),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='payment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='watched',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='watchlater',
            unique_together={('Show_id', 'User_id')},
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Netflix.country'),
        ),
    ]
